project:
  type: site
  resources:
    - "*.xlsx"

website:
  title: "Matt Worthington"
  twitter-card: true
  site-url: https://www.mrworthington.com
  open-graph: true
  reader-mode: false
  page-navigation: false
  google-analytics:
    tracking-id: "UA-52682113"
    storage: cookies
    anonymize-ip: true
    version: 4
  # page-footer:
  #   center:
  #     - text: "About Me"
  #       href: about.qmd
  #     - text: "License"
  #       href: license.qmd
  #     - text: "Trademark"
  #       href: trademark.qmd
  search:
   location: navbar
   type: overlay
  cookie-consent:
    type: implied
    style: simple
    palette: light
  navbar:
    type: dark
    logo: logo.png
    pinned: true
    background: primary
    search: false
    collapse-below: lg
    left:
      - href: index.qmd
        text: Home
        aria-label: "The Home Page"
      - href: about.qmd
        text: About Me
        aria-label: "The About Page"
      - href: https://portfolio.mrworthington.com/
        text: Portfolio
        aria-label: "Link to My Portfolio"
      # - text: "Get Started"
      #   href: docs/get-started/index.qmd
    right:
      - href: https://github.com/mrworthington
        icon: github
        aria-label: "Link to My Github"
      - href: https://twitter.com/mrworthington
        icon: twitter
        aria-label: "Link to My Twitter"
      - icon: rss
        href: index.xml

  # footer:
  #   border: true
  #   left: "Copyright 2021, Norah Jones"
  #   right:
  #     - icon: github
  #       href: https://github.com/mrworthington
  #       aria-label: "Link to My Github"
  #     - icon: twitter
  #       href: https://twitter.com/mrworthington
  #       aria-label: "Link to My Twitter"
  # sidebar:
  #   # border: true
  # - id: get-started
  #   title: "Get Started"
  #   subtitle: "Subtitle"
  #   style: "docked"
  #   collapse-level: 1
  #   # logo: https://mattfortexas51.com/2.svg
  #   tools:
  #     - icon: twitter
  #       href: https://twitter.com
  #   # search: true
  #   # align: left
  #   contents:
  #   - section: "Authoring"
  #     contents:
  #       - docs/get-started/index.qmd
  #       - text: "Hello, Quarto"
  #         href: google.com
  #       - text: "Computations"
  #         href: twitter.com
  #       - text: "Authoring"
  #         href: facebook.com
  #   - section: "Publishing"
  #     contents:
  #       - docs/get-started/index.qmd
  #       - text: "Hello, Quarto"
  #         href: google.com
  #       - text: "Computations"
  #         href: twitter.com
  #       - text: "Authoring"
  #         href: facebook.com
  #   - section: "Editing"
  #     contents:
  #       - docs/get-started/index.qmd
  #       - text: "Hello, Quarto"
  #         href: google.com
  #       - text: "Computations"
  #         href: twitter.com
  #       - text: "Authoring"
  #         href: facebook.com
  #   - section: "Examples"
  #     contents:
  #       - docs/get-started/index.qmd
  #       - text: "Hello, Quarto"
  #         href: google.com
  #       - text: "Computations"
  #         href: twitter.com
  #       - text: "Authoring"
  #         href: facebook.com
  # - id: tutorials
  #   title: "Tutorials"
  #   style: "docked"
  #   collapse-level: 1
  #   # search: true
  #   align: left
  #   contents:
  #     - docs/tutorials/index.qmd
  #     - text: "Hello, Quarto"
  #       href: google.com
  #     - text: "Computations"
  #       href: twitter.com
  #     - text: "Authoring"
  #       href: facebook.com

format:
  html:
    include-in-header:
    - header.html
    lang: en
    # code-tools:
    #   source: false
    #   toggle: true
    anchor-sections: true
    link-external-icon: false
    link-external-newwindow: true
    callout-appearance: simple
    theme:
      light: custom.scss
      # dark: darkly
    toc: true

freeze: auto
