project:
  type: site
  resources:
    - "*.xlsx"

website:
  title: "Matt Worthington"
  repository_url: https://github.com/mrworthington/mrworthington.github.io
  google-analytics: "UA-52682113-1"
  twitter-card: true
  opengraph: true
  reader-mode: false
  page-navigation: false
  page-footer:
    center:
      - text: "About Me"
        href: about.qmd
      - text: "License"
        href: license.qmd
      - text: "Trademark"
        href: trademark.qmd
  search:
   location: navbar
   type: overlay
  cookie-consent:
    type: implied
    style: simple
    palette: light
  navbar:
    type: dark
    logo: logo.png
    pinned: true
    background: primary
    search: false
    collapse-below: lg
    left:
      - href: index.qmd
        text: Home
        aria-label: "The Home Page"
      - href: about.qmd
        text: About Me
        aria-label: "The About Page"
      - href: https://portfolio.mrworthington.com/
        text: Portfolio
        aria-label: "Link to My Portfolio"
      # - text: "Get Started"
      #   href: docs/get-started/index.qmd
    right:
      - href: https://github.com/mrworthington
        icon: github
        aria-label: "Link to My Github"
      - href: https://twitter.com/mrworthington
        icon: twitter
        aria-label: "Link to My Twitter"
  footer:
    border: true
    left: "Copyright 2021, Norah Jones"
    right:
      - icon: github
        href: https://github.com/mrworthington
        aria-label: "Link to My Github"
      - icon: twitter
        href: https://twitter.com/mrworthington
        aria-label: "Link to My Twitter"

format:
  html:
    include-in-header:
    - header.html
    lang: en
    # code-tools:
    #   source: false
    #   toggle: true
    anchor-sections: true
    link-external-icon: false
    link-external-newwindow: true
    callout-appearance: simple
    theme:
      light: custom.scss
      # dark: darkly
    toc: true
