[context.production]
  command = ""
  publish = ""
  
[context.blog]
    command = "hugo"
    publish = "public"
    HUGO_VERSION = "0.36"
    RUBY_VERSION = "2.2.9"

[context.branch-deploy]
    command = "hugo"
    publish = "public"
    HUGO_VERSION = "0.36"
    RUBY_VERSION = "2.2.9"
