[context.production]
  command = ""
  publish = ""

[context.blog]
    command = "hugo"
    publish = "public"

  [context.blog.environment]
    RUBY_VERSION = "2.6.2"
    HUGO_VERSION = "0.74.1"
    

[context.dev-site]
    command = "hugo"
    publish = "public"

  [context.dev-site.environment]
    RUBY_VERSION = "2.6.2"
    HUGO_VERSION = "0.74.1"

[context.branch-deploy]
    command = "hugo"
    publish = "public"

  [context.branch-deploy.environment]
    RUBY_VERSION = "2.6.2"
    HUGO_VERSION = "0.74.1"
