[context.production]
  command = ""
  publish = ""

[context.branch-deploy]
    command = "hugo"
    publish = "public"

  [context.branch-deploy.environment]
    RUBY_VERSION = "2.6.2"
    HUGO_VERSION = "0.74.1"
