[context.production]
  command = ""
  publish = ""

[context.branch-deploy]
    command = "hugo"
    publish = "public"
    HUGO_VERSION = "0.36"

[context.blog]
  command = "hugo"
  publish = "public"
  HUGO_VERSION = "0.36"
