---
author: Matt Worthington
draft: false
title: My Resume
subtitle: As of `r format(Sys.Date(), "%B %Y")`
output:
  html_document: 
    toc: yes
    toc_float: true
---

## <a style="font-weight:900;text-transform:capitalize;color:#3d3d3d">Education</a>
***
#### **[The University of Texas at Austin, LBJ School of Public Affairs](https://lbj.utexas.edu)** <a style="font-weight:200;color:#9cadb7">—*Austin, TX*</a><a style="float:right;color:#9cadb7">Exp. 2018</a> 
#### Master of Public Affairs, Merit Fellowship Recipient
* Policy Research: Crafting a 2-Generation Strategy for Central Texas and Outlining an Approach for Measuring its Results

#### **[George Mason University](https://www2.gmu.edu)**</a><a style="color:#9cadb7">—*Fairfax, VA*</a><a style="float:right;color:#9cadb7">May 2011</a> 
#### Master of Education in Special Education
* Licensure: DC Teaching Licensure in Special Education
* Distinctions: Teach For America Corps & Phi Kappa Phi 

#### **[Abilene Christian University](http://acu.edu)** <a style="color:#9cadb7">—*Abilene, TX*</a><a style="float:right;color:#9cadb7">December 2008</a> 
                                                                                                
#### Bachelor of Arts in English, 
* Distinctions: Servant-Leader Distinction & Dean’s Honor Roll


## <a style="font-weight:900;text-transform:capitalize;color:#3d3d3d">Professional Experience</a>
***
### **Research & Reporting Analyst** <a style="font-weight:200;color:#9cadb7"> | *[Folo Media](https://www.folomedia.org/about/)*</a><a style="float:right;color:#9cadb7">Jun-Dec 2017</a> 
* **Strategic Planning**: Consulted with eight school leaders annually to plan end-to-end digital learning solutions that are aligned to regional priorities, budget conscious, and have quantifiable metrics for tracking growth.
* **Curriculum Development**: Functioned as a member of a heavyweight team (12-15 members from the region) to evaluate regional needs in secondary math and literacy, plan data-driven solutions based off those needs, and implement annual curriculum priorities in as well as consulting for the elementary math and literacy teams.
* **Project Management**: Established all annual timelines, deadlines, and deliverables for all stakeholders across nine schools to enroll 4,000 students in multiple online learning programs.
* **Staff Development**: Increased staff digital learning competencies & institutional knowledge through in-person and online professional development facilitated through a suite of over 100 online resources built in-house.

### **Graduate Assistant** <a style="font-weight:200;color:#9cadb7"> | *[DDCE @ UT Austin](http://diversity.utexas.edu)*</a><a style="float:right;color:#9cadb7">Feb-May 2017</a> 
* **Strategic Planning**: Consulted with eight school leaders annually to plan end-to-end digital learning solutions that are aligned to regional priorities, budget conscious, and have quantifiable metrics for tracking growth.
* **Curriculum Development**: Functioned as a member of a heavyweight team (12-15 members from the region) to evaluate regional needs in secondary math and literacy, plan data-driven solutions based off those needs, and implement annual curriculum priorities in as well as consulting for the elementary math and literacy teams.
* **Project Management**: Established all annual timelines, deadlines, and deliverables for all stakeholders across nine schools to enroll 4,000 students in multiple online learning programs.
* **Staff Development**: Increased staff digital learning competencies & institutional knowledge through in-person and online professional development facilitated through a suite of over 100 online resources built in-house.

#### **Digital Learning Coordinator** <a style="font-weight:200;color:#9cadb7"> | *[KIPP Austin Public Schools](http://www.kippaustin.org)*</a><a style="float:right;color:#9cadb7">2013-2016</a> 
* **Strategic Planning**: Consulted with eight school leaders annually to plan end-to-end digital learning solutions that are aligned to regional priorities, budget conscious, and have quantifiable metrics for tracking growth.
* **Curriculum Development**: Functioned as a member of a heavyweight team (12-15 members from the region) to evaluate regional needs in secondary math and literacy, plan data-driven solutions based off those needs, and implement annual curriculum priorities in as well as consulting for the elementary math and literacy teams.
* **Project Management**: Established all annual timelines, deadlines, and deliverables for all stakeholders across nine schools to enroll 4,000 students in multiple online learning programs.
* **Staff Development**: Increased staff digital learning competencies & institutional knowledge through in-person and online professional development facilitated through a suite of over 100 online resources built in-house.

#### **Manager of Technology Strategy** <a style="font-weight:200;color:#9cadb7"> | *KIPP Austin Public Schools*</a><a style="float:right;color:#9cadb7">2012-2013</a> 
* **Strategic Planning**: Consulted with eight school leaders annually to plan end-to-end digital learning solutions that are aligned to regional priorities, budget conscious, and have quantifiable metrics for tracking growth.
* **Curriculum Development**: Functioned as a member of a heavyweight team (12-15 members from the region) to evaluate regional needs in secondary math and literacy, plan data-driven solutions based off those needs, and implement annual curriculum priorities in as well as consulting for the elementary math and literacy teams.
* **Project Management**: Established all annual timelines, deadlines, and deliverables for all stakeholders across nine schools to enroll 4,000 students in multiple online learning programs.
* **Staff Development**: Increased staff digital learning competencies & institutional knowledge through in-person and online professional development facilitated through a suite of over 100 online resources built in-house.

#### **Digital Learning Coordinator** <a style="font-weight:200;color:#9cadb7"> | *KIPP Austin Public Schools*</a><a style="float:right;color:#9cadb7">2009-2012</a> 
* **Strategic Planning**: Consulted with eight school leaders annually to plan end-to-end digital learning solutions that are aligned to regional priorities, budget conscious, and have quantifiable metrics for tracking growth.
* **Curriculum Development**: Functioned as a member of a heavyweight team (12-15 members from the region) to evaluate regional needs in secondary math and literacy, plan data-driven solutions based off those needs, and implement annual curriculum priorities in as well as consulting for the elementary math and literacy teams.
* **Project Management**: Established all annual timelines, deadlines, and deliverables for all stakeholders across nine schools to enroll 4,000 students in multiple online learning programs.
* **Staff Development**: Increased staff digital learning competencies & institutional knowledge through in-person and online professional development facilitated through a suite of over 100 online resources built in-house.

## <a style="font-weight:900;text-transform:capitalize;color:#3d3d3d">Volunteer Experience</a>
***
#### **DIGITAL LEARNING COORDINATOR** <a style="font-weight:200;color:#9cadb7"> | *KIPP Austin Public Schools*</a><a style="float:right;color:#9cadb7">2012-2013</a> 
* **Strategic Planning**: Consulted with eight school leaders annually to plan end-to-end digital learning solutions that are aligned to regional priorities, budget conscious, and have quantifiable metrics for tracking growth.
* **Curriculum Development**: Functioned as a member of a heavyweight team (12-15 members from the region) to evaluate regional needs in secondary math and literacy, plan data-driven solutions based off those needs, and implement annual curriculum priorities in as well as consulting for the elementary math and literacy teams.
* **Project Management**: Established all annual timelines, deadlines, and deliverables for all stakeholders across nine schools to enroll 4,000 students in multiple online learning programs.
* **Staff Development**: Increased staff digital learning competencies & institutional knowledge through in-person and online professional development facilitated through a suite of over 100 online resources built in-house.

#### **DIGITAL LEARNING COORDINATOR** <a style="font-weight:200;color:#9cadb7"> | *KIPP Austin Public Schools*</a><a style="float:right;color:#9cadb7">2012-2013</a> 
* **Strategic Planning**: Consulted with eight school leaders annually to plan end-to-end digital learning solutions that are aligned to regional priorities, budget conscious, and have quantifiable metrics for tracking growth.
* **Curriculum Development**: Functioned as a member of a heavyweight team (12-15 members from the region) to evaluate regional needs in secondary math and literacy, plan data-driven solutions based off those needs, and implement annual curriculum priorities in as well as consulting for the elementary math and literacy teams.
* **Project Management**: Established all annual timelines, deadlines, and deliverables for all stakeholders across nine schools to enroll 4,000 students in multiple online learning programs.
* **Staff Development**: Increased staff digital learning competencies & institutional knowledge through in-person and online professional development facilitated through a suite of over 100 online resources built in-house.

#### **DIGITAL LEARNING COORDINATOR** <a style="font-weight:200;color:#9cadb7"> | *KIPP Austin Public Schools*</a><a style="float:right;color:#9cadb7">2012-2013</a> 
* **Strategic Planning**: Consulted with eight school leaders annually to plan end-to-end digital learning solutions that are aligned to regional priorities, budget conscious, and have quantifiable metrics for tracking growth.
* **Curriculum Development**: Functioned as a member of a heavyweight team (12-15 members from the region) to evaluate regional needs in secondary math and literacy, plan data-driven solutions based off those needs, and implement annual curriculum priorities in as well as consulting for the elementary math and literacy teams.
* **Project Management**: Established all annual timelines, deadlines, and deliverables for all stakeholders across nine schools to enroll 4,000 students in multiple online learning programs.
* **Staff Development**: Increased staff digital learning competencies & institutional knowledge through in-person and online professional development facilitated through a suite of over 100 online resources built in-house.

#### **DIGITAL LEARNING COORDINATOR** <a style="font-weight:200;color:#9cadb7"> | *KIPP Austin Public Schools*</a><a style="float:right;color:#9cadb7">2012-2013</a> 
* **Strategic Planning**: Consulted with eight school leaders annually to plan end-to-end digital learning solutions that are aligned to regional priorities, budget conscious, and have quantifiable metrics for tracking growth.
* **Curriculum Development**: Functioned as a member of a heavyweight team (12-15 members from the region) to evaluate regional needs in secondary math and literacy, plan data-driven solutions based off those needs, and implement annual curriculum priorities in as well as consulting for the elementary math and literacy teams.
* **Project Management**: Established all annual timelines, deadlines, and deliverables for all stakeholders across nine schools to enroll 4,000 students in multiple online learning programs.
* **Staff Development**: Increased staff digital learning competencies & institutional knowledge through in-person and online professional development facilitated through a suite of over 100 online resources built in-house.