my_hc_theme <- function(base_size="12px", base_family="Cabin", title_size="28px", title_weight = "800", subtitle_size="14px", subtitle_weight = "400",
                          credit_size="10px", header_align = "left", legend_align = "center", credits_align = "left", ...) {

  highcharter::hc_theme_merge(
    highcharter::hc_theme_smpl(),
    highcharter::hc_theme(colors = c("#002D74", "#F26852", "#2A7DE1", "#00A9C5", "#3A4A9F"),
                          marker = list(fillColor = c("#002D74", "#F26852", "#2A7DE1", "#00A9C5", "#3A4A9F"),
                                        lineColor = '#000',
                                        radius = 3,
                                        lineWidth = 1,
                                        symbol = "circle"),
                          chart = list(backgroundColor = "#fff",
                                       style = list(fontFamily = base_family,
                                                    fontSize = base_size,
                                                    color="#2d2d2d",
                                                    fontWeight="500",
                                                    textTransform="initial")),
                          title = list(style = list(fontFamily = base_family,
                                                    fontSize = title_size,
                                                    fontWeight = title_weight,
                                                    color="#2d2d2d"),
                                       align = header_align),
                          subtitle = list(style = list(fontFamily = base_family,
                                                       color="#2d2d2d",
                                                       textTransform="initial",
                                                       fontWeight=subtitle_weight,
                                                       fontSize = subtitle_size),
                                          align = header_align),
                          legend = list(align = legend_align,
                                        style = list(fontFamily = base_family,
                                                     color="white"),
                                        itemStyle = list(fontFamily = base_family,
                                                         color = '#2d2d2d'),
                                        itemHoverStyle = list(color = 'gray'),
                                        verticalAlign = "top"),
                          credits = list(style = list(color = "#2d2d2d",
                                                      fontSize = credit_size),
                                         align = credits_align),
                          tooltip = list(
                            backgroundColor = "#ffffff",
                            borderColor = "#333f48",
                            borderRadius = 2,
                            borderWidth = 3,
                            shape = "rect",
                            className = "highchart-ttip-style",
                            padding = 4
                          ),
                          xAxis = list(labels = list(style = list(fontFamily = "JetBrains Mono, sans-serif",
                                                                  color = "#3C3C3C")),
                                       title = list(style = list(color = "#2d2d2d",
                                                                 fontSize = "12px",
                                                                 color="#2d2d2d",
                                                                 fontWeight="500")),
                                       lineColor = '#2d2d2d',
                                       lineWidth = 2,
                                       gridLineWidth = 0,
                                       gridLineColor = 'rgba(219,220,221,1)',
                                       tickColor = 'rgba(219,220,221,1)',
                                       tickWidth = 1),
                          yAxis = list(labels = list(style = list(fontFamily = "JetBrains Mono, sans-serif",
                                                                  color = "#3C3C3C")),
                                       title = list(style = list(color = "#2d2d2d",
                                                                 fontSize = "12px",
                                                                 color="#2d2d2d",
                                                                 fontWeight="500")),
                                       gridLineWidth = 0.75,
                                       lineColor = 'rgba(219,220,221,0.5)',
                                       lineWidth = 0,
                                       MinorGridLineWidth = 0.75,
                                       MinorGridLineColor = 'rgba(219,220,221,0.5)',
                                       gridLineWidth = 0.75,
                                       gridLineColor = 'rgba(219,220,221,0.5)',
                                       tickColor = 'rgba(219,220,221,1)',
                                       tickWidth = 1),
                          plotOptions = list(column = list(opacity=.8,
                                                           groupPadding = 0,
                                                           # pointWidth = 35,
                                                           dataLabels = list(
                                                             style = list(fontFamily = "JetBrains Mono, sans-serif",
                                                                          color = "#3C3C3C")
                                                           )))))

}
